import { Inter } from 'next/font/google'
import Header from "@/components/Header"
import Footer from "@/components/Footer"
import Head from 'next/head'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
      </Head>
      <body className={`${inter.className} bg-gray-900 w-full h-full`}>
        <Header />
        <main>
          {children}
        </main>
        <Footer />
      </body>
    </html >
  )
}
